### ISSUE TITLE
Warning Keeps Showing Up Even After User is Signed In

### ISSUE THREAD

**Issue by VictorOhachor** [TNSQUAD/PhoenixMart#4]
![image](https://github.com/TNSQUAD/PhoenixMart/assets/114190932/7bd74c57-0a74-423c-ac64-c748c5e73ca6)

This warning:
_You need to login before accessing your wishlist._

Keeps showing up whenever I reload a page or visit any page, even when I am signed in.

**Comment by Rachamv** [comment]
Wishlist Login warning error fix
